# Generated by Django 5.2.7 on 2025-10-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Nomor urut untuk sorting')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='SubBab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Teks unik untuk URL, e.g., 'perhitungan-harga-jual'", unique=True)),
                ('konten', models.TextField(help_text='Isi materi di sini. Bisa menggunakan HTML.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('bab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbab_list', to='pembelajaran.bab')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
    ]
