# Generated by Django 5.2.7 on 2025-11-20 13:20

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Nomor urut untuk sorting')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='GameDragDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Game Interaktif: Sortir Biaya', max_length=255)),
                ('instruksi', models.TextField(default='Tarik dan lepas setiap item ke kategori yang benar.')),
                ('nama_kategori_benar', models.CharField(default='Biaya Tetap', max_length=100)),
                ('nama_kategori_salah', models.CharField(default='Bukan Biaya Tetap', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Game Drag & Drop',
            },
        ),
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Kuis Pemahaman', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kuis',
            },
        ),
        migrations.CreateModel(
            name='ItemDragDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_item', models.CharField(max_length=100)),
                ('gambar_item', models.ImageField(blank=True, help_text='Opsional. Gambar untuk item (misal: foto tepung).', null=True, upload_to='game_items/')),
                ('is_kategori_benar', models.BooleanField(default=True, help_text="Centang jika ini termasuk 'Kategori Benar' (misal: Biaya Tetap)")),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='pembelajaran.gamedragdrop')),
            ],
            options={
                'ordering': ['teks_item'],
            },
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pertanyaan', ckeditor.fields.RichTextField(help_text='Tulis teks pertanyaan di sini.')),
                ('penjelasan_jawaban', ckeditor.fields.RichTextField(blank=True, help_text='Penjelasan detail mengapa jawaban ini benar/salah.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan_set', to='pembelajaran.kuis')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=500)),
                ('is_jawaban_benar', models.BooleanField(default=False)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_set', to='pembelajaran.pertanyaan')),
            ],
        ),
        migrations.CreateModel(
            name='SubBab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Teks unik untuk URL, misalnya 'perhitungan-harga-jual'", unique=True)),
                ('konten', ckeditor.fields.RichTextField(help_text='Isi materi di sini')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('bab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbab_list', to='pembelajaran.bab')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='StudiKasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Studi Kasus', max_length=255)),
                ('kasus', ckeditor.fields.RichTextField(help_text='Jelaskan situasi atau masalah dalam studi kasus.')),
                ('pertanyaan', ckeditor.fields.RichTextField(help_text='Tuliskan pertanyaan yang harus dijawab oleh pengguna.')),
                ('pembahasan', ckeditor.fields.RichTextField(help_text='Jelaskan pembahasan atau jawaban dari studi kasus.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('subbab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studi_kasus', to='pembelajaran.subbab')),
            ],
            options={
                'verbose_name_plural': 'Studi Kasus',
                'ordering': ['urutan'],
            },
        ),
        migrations.AddField(
            model_name='kuis',
            name='subbab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kuis', to='pembelajaran.subbab'),
        ),
        migrations.AddField(
            model_name='gamedragdrop',
            name='subbab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_drag_drop', to='pembelajaran.subbab'),
        ),
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.PositiveIntegerField(default=0)),
                ('total_soal', models.PositiveIntegerField(default=0)),
                ('tanggal_mengerjakan', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to=settings.AUTH_USER_MODEL)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_user', to='pembelajaran.kuis')),
            ],
            options={
                'verbose_name_plural': 'Hasil Kuis',
                'ordering': ['-tanggal_mengerjakan'],
                'unique_together': {('user', 'kuis')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('subbab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembelajaran.subbab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'subbab')},
            },
        ),
    ]
