# Generated by Django 5.2.7 on 2025-10-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudiKasus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Studi Kasus', max_length=255)),
                ('kasus', models.TextField(help_text='Jelaskan situasi atau masalah dalam studi kasus.')),
                ('pertanyaan', models.TextField(help_text='Tuliskan pertanyaan yang harus dijawab oleh pengguna.')),
                ('pembahasan', models.TextField(help_text='Jelaskan pembahasan atau jawaban dari studi kasus.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('subbab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studi_kasus', to='pembelajaran.subbab')),
            ],
            options={
                'verbose_name_plural': 'Studi Kasus',
                'ordering': ['urutan'],
            },
        ),
    ]
