# Generated by Django 5.2.7 on 2025-10-17 03:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0002_studikasus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studikasus',
            name='kasus',
            field=ckeditor.fields.RichTextField(help_text='Jelaskan situasi atau masalah dalam studi kasus.'),
        ),
        migrations.AlterField(
            model_name='studikasus',
            name='pembahasan',
            field=ckeditor.fields.RichTextField(help_text='Jelaskan pembahasan atau jawaban dari studi kasus.'),
        ),
        migrations.AlterField(
            model_name='studikasus',
            name='pertanyaan',
            field=ckeditor.fields.RichTextField(help_text='Tuliskan pertanyaan yang harus dijawab oleh pengguna.'),
        ),
        migrations.AlterField(
            model_name='subbab',
            name='konten',
            field=ckeditor.fields.RichTextField(help_text='Isi materi di sini tanpa perlu menulis HTML.'),
        ),
        migrations.AlterField(
            model_name='subbab',
            name='slug',
            field=models.SlugField(help_text="Teks unik untuk URL, misalnya 'perhitungan-harga-jual'", unique=True),
        ),
    ]
