# Generated by Django 5.2.7 on 2025-10-24 05:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0003_alter_studikasus_kasus_alter_studikasus_pembahasan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subbab',
            name='konten',
            field=ckeditor.fields.RichTextField(help_text='Isi materi di sini'),
        ),
    ]
