# Generated by Django 5.2.7 on 2025-10-31 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0004_alter_subbab_konten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Kuis Pemahaman', max_length=255)),
                ('subbab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kuis', to='pembelajaran.subbab')),
            ],
            options={
                'verbose_name_plural': 'Kuis',
            },
        ),
        migrations.CreateModel(
            name='Pertanyaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pertanyaan', models.TextField()),
                ('penjelasan_jawaban', models.TextField(blank=True, help_text='Penjelasan detail mengapa jawaban ini benar/salah.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pertanyaan_set', to='pembelajaran.kuis')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=500)),
                ('is_jawaban_benar', models.BooleanField(default=False)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_set', to='pembelajaran.pertanyaan')),
            ],
        ),
    ]
