# Generated by Django 5.2.7 on 2025-10-31 06:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0005_kuis_pertanyaan_pilihan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='penjelasan_jawaban',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Penjelasan detail mengapa jawaban ini benar/salah.'),
        ),
        migrations.AlterField(
            model_name='pertanyaan',
            name='teks_pertanyaan',
            field=ckeditor.fields.RichTextField(help_text='Tulis teks pertanyaan di sini.'),
        ),
        migrations.CreateModel(
            name='GameDragDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Game Interaktif: Sortir Biaya', max_length=255)),
                ('instruksi', models.TextField(default='Tarik dan lepas setiap item ke kategori yang benar.')),
                ('nama_kategori_benar', models.CharField(default='Biaya Tetap', max_length=100)),
                ('nama_kategori_salah', models.CharField(default='Bukan Biaya Tetap', max_length=100)),
                ('subbab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_drag_drop', to='pembelajaran.subbab')),
            ],
            options={
                'verbose_name_plural': 'Game Drag & Drop',
            },
        ),
        migrations.CreateModel(
            name='ItemDragDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_item', models.CharField(max_length=100)),
                ('gambar_item', models.ImageField(blank=True, help_text='Opsional. Gambar untuk item (misal: foto tepung).', null=True, upload_to='game_items/')),
                ('is_kategori_benar', models.BooleanField(default=True, help_text="Centang jika ini termasuk 'Kategori Benar' (misal: Biaya Tetap)")),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='pembelajaran.gamedragdrop')),
            ],
            options={
                'ordering': ['teks_item'],
            },
        ),
    ]
