# Generated by Django 5.2.7 on 2025-11-16 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0007_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilKuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.PositiveIntegerField(default=0)),
                ('total_soal', models.PositiveIntegerField(default=0)),
                ('tanggal_mengerjakan', models.DateTimeField(auto_now=True)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_user', to='pembelajaran.kuis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hasil Kuis',
                'ordering': ['-tanggal_mengerjakan'],
                'unique_together': {('user', 'kuis')},
            },
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
