# Generated by Django 5.2.7 on 2025-11-21 04:12

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0009_alter_hasilkuis_tanggal_mengerjakan_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Latihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul Latihan')),
                ('deskripsi', ckeditor.fields.RichTextField(help_text='Instruksi pengerjaan latihan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_bab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_latihan', to='pembelajaran.subbab')),
            ],
            options={
                'verbose_name': 'Latihan',
                'verbose_name_plural': 'Latihan',
            },
        ),
        migrations.CreateModel(
            name='HasilLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_jawaban', models.FileField(blank=True, null=True, upload_to='uploads/latihan/', verbose_name='File Jawaban')),
                ('text_jawaban', models.TextField(blank=True, null=True, verbose_name='Jawaban Teks')),
                ('nilai', models.IntegerField(default=0, verbose_name='Nilai (0-100)')),
                ('feedback_guru', models.TextField(blank=True, null=True, verbose_name='Komentar Guru')),
                ('tanggal_kumpul', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_latihan', to=settings.AUTH_USER_MODEL)),
                ('latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_siswa', to='pembelajaran.latihan')),
            ],
            options={
                'verbose_name': 'Hasil Latihan',
                'verbose_name_plural': 'Hasil Latihan',
            },
        ),
    ]
