# Generated by Django 5.2.7 on 2025-11-21 05:06

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0010_latihan_hasillatihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pertanyaan', ckeditor.fields.RichTextField(help_text='Tulis pertanyaan latihan di sini.')),
                ('penjelasan_jawaban', ckeditor.fields.RichTextField(blank=True, help_text='Penjelasan detail jawaban.')),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daftar_soal', to='pembelajaran.latihan')),
            ],
            options={
                'verbose_name': 'Soal Latihan',
                'verbose_name_plural': 'Soal Latihan',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='PilihanLatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=500)),
                ('is_jawaban_benar', models.BooleanField(default=False, verbose_name='Is Jawaban Benar')),
                ('soal_latihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan_latihan_set', to='pembelajaran.soallatihan')),
            ],
        ),
    ]
