# Generated by Django 5.2.7 on 2025-11-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0011_soallatihan_pilihanlatihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField(help_text='Pertanyaan evaluasi akhir.')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Soal Evaluasi',
            },
        ),
        migrations.CreateModel(
            name='PilihanJawaban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_pilihan', models.CharField(max_length=255)),
                ('apakah_benar', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='pembelajaran.soalevaluasi')),
            ],
            options={
                'verbose_name_plural': 'Pilihan Jawaban',
            },
        ),
    ]
