# Generated by Django 5.2.7 on 2025-11-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0012_soalevaluasi_pilihanjawaban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaan',
            name='penjelasan_jawaban',
        ),
    ]
