# Generated by Django 5.2.7 on 2025-11-28 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0013_remove_pertanyaan_penjelasan_jawaban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanGuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkm_kuis', models.IntegerField(default=75, verbose_name='KKM Kuis')),
                ('kkm_evaluasi', models.IntegerField(default=80, verbose_name='KKM Evaluasi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pengaturan_guru', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Guru',
                'verbose_name_plural': 'Pengaturan Guru',
            },
        ),
    ]
