# Generated by Django 5.2.7 on 2025-11-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0013_remove_pertanyaan_penjelasan_jawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedragdrop',
            name='gambar_sampul',
            field=models.ImageField(blank=True, help_text='Upload foto ilustrasi atau cover untuk game ini.', null=True, upload_to='game_covers/'),
        ),
    ]
