# Generated by Django 5.2.7 on 2025-12-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0014_pengaturanguru'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanguru',
            name='kkm_latihan',
            field=models.IntegerField(default=70, verbose_name='KKM Latihan'),
        ),
    ]
