# Generated by Django 5.2.7 on 2025-12-05 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0014_gamedragdrop_gambar_sampul'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilEvaluasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField(default=0)),
                ('total_soal', models.IntegerField(default=0)),
                ('tanggal_mengerjakan', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_evaluasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hasil Evaluasi Akhir',
            },
        ),
    ]
