# Generated by Django 5.2.7 on 2025-12-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0015_hasilevaluasi'),
        ('pembelajaran', '0015_pengaturanguru_kkm_latihan'),
    ]

    operations = [
    ]
