# Generated by Django 5.2.7 on 2025-12-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0016_merge_20251206_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soalevaluasi',
            options={'ordering': ['urutan'], 'verbose_name_plural': 'Soal Evaluasi'},
        ),
        migrations.AddField(
            model_name='soalevaluasi',
            name='urutan',
            field=models.PositiveIntegerField(default=0, help_text='Nomor urut soal'),
        ),
    ]
