# Generated by Django 5.2.7 on 2025-12-09 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0017_alter_soalevaluasi_options_soalevaluasi_urutan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbab',
            name='tujuan_pembelajaran',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Isi tujuan pembelajaran (poin-poin) yang akan dicapai siswa di sub-bab ini.', null=True),
        ),
    ]
