# Generated by Django 5.2.7 on 2025-12-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0018_subbab_tujuan_pembelajaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbab',
            name='tujuan_pembelajaran',
        ),
    ]
