# Generated by Django 5.2.7 on 2025-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0019_remove_subbab_tujuan_pembelajaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuis',
            name='durasi',
            field=models.IntegerField(default=10, help_text='Durasi kuis dalam menit'),
        ),
    ]
