# Generated by Django 5.2.7 on 2025-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0020_kuis_durasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilkuis',
            name='lama_pengerjaan',
            field=models.IntegerField(default=0, help_text='Lama pengerjaan dalam detik'),
        ),
    ]
