# Generated by Django 5.2.7 on 2025-12-14 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0021_hasilkuis_lama_pengerjaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latihan',
            name='sub_bab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='latihan', to='pembelajaran.subbab'),
        ),
    ]
