# Generated by Django 5.2.7 on 2025-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0022_alter_latihan_sub_bab'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilevaluasi',
            name='lama_pengerjaan',
            field=models.IntegerField(default=0, help_text='Lama pengerjaan dalam detik'),
        ),
    ]
