# Generated by Django 5.2.7 on 2025-12-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0023_hasilevaluasi_lama_pengerjaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaturanguru',
            name='durasi_evaluasi',
            field=models.IntegerField(default=30, verbose_name='Durasi Evaluasi (Menit)'),
        ),
    ]
