# Generated by Django 5.2.7 on 2025-12-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pembelajaran', '0024_pengaturanguru_durasi_evaluasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latihan',
            name='deskripsi',
        ),
    ]
